name: Feature request / 功能建议
description: An idea to make it better / 想要的功能
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: what
    attributes:
      label: What would you like? / 你想要什么
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful? / 为什么有用
      description: 你想解决的问题，而不只是方案 / The problem you're solving, not just the solution
    validations:
      required: false
